# Generated by Django 3.2.9 on 2022-01-20 09:23

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_ticketmodel_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticketmodel',
            name='date',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now),
        ),
    ]
