# Generated by Django 3.2.9 on 2022-01-26 17:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_ticketmodel_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ticketmodel',
            options={'permissions': (('create_tickets', 'can create tickets'), ('rewrite_tickets', 'can change tickets'), ('answer_tickets', 'can answer tickets'))},
        ),
    ]
