# Generated by Django 3.2.9 on 2022-01-26 19:00

from django.db import migrations, models
import email.utils


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_ticketmodel_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticketmodel',
            name='date',
            field=models.DateTimeField(blank=True, default=email.utils.localtime),
        ),
    ]
