# Generated by Django 3.2.9 on 2022-01-26 19:22

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_alter_ticketmodel_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticketmodel',
            name='date',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.localtime),
        ),
    ]
