# Generated by Django 3.2.9 on 2022-01-26 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_alter_ticketmodel_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticketmodel',
            name='date',
            field=models.DateTimeField(blank=True, default='Jan. 26, 2022, 19-36-42, 07:36 PM'),
        ),
    ]
