# Generated by Django 3.2.9 on 2022-01-26 19:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_alter_ticketmodel_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticketmodel',
            name='date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 1, 26, 19, 38, 30, 401074)),
        ),
    ]
