# Generated by Django 3.2.9 on 2022-01-27 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_alter_ticketmodel_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticketmodel',
            name='priorities',
            field=models.CharField(choices=[('U', 'Urgent'), ('H', 'High'), ('M', 'Medium'), ('L', 'Low')], default='L', max_length=1),
        ),
    ]
