# Generated by Django 3.2.9 on 2022-01-27 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_ticketmodel_priorities'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticketmodel',
            name='type',
            field=models.CharField(choices=[('Q', 'Question'), ('P', 'Problem'), ('I', 'Incident'), ('R', 'Request'), ('O', 'Order')], default='Q', max_length=1),
        ),
    ]
