# Generated by Django 3.2.9 on 2022-01-27 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_ticketmodel_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticketmodel',
            name='priorities',
            field=models.CharField(choices=[('1', 'Urgent'), ('2', 'High'), ('3', 'Medium'), ('4', 'Low')], default='4', max_length=1),
        ),
    ]
