# Generated by Django 3.2.9 on 2022-01-27 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_auto_20220127_0946'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticketmodel',
            name='num_answers',
            field=models.IntegerField(default=0),
        ),
    ]
