# Generated by Django 3.2.9 on 2022-01-27 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_ticketmodel_num_answers'),
    ]

    operations = [
        migrations.AddField(
            model_name='answermodel',
            name='number',
            field=models.IntegerField(default=0),
        ),
    ]
