# Generated by Django 3.2.9 on 2022-02-04 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_answermodel_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticketmodel',
            name='title',
            field=models.TextField(default='Title'),
        ),
    ]
