# Generated by Django 3.2.9 on 2022-02-09 15:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0019_alter_ticketmodel_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='answermodel',
            name='answer_comments',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='ticketmodel',
            name='ticket_comments',
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name='CommentModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(default='T')),
                ('number', models.IntegerField(default=0)),
                ('answer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.answermodel')),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.ticketmodel')),
            ],
        ),
    ]
