# Generated by Django 3.2.9 on 2022-02-09 18:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0020_auto_20220209_1534'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommentAnswerModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(default='T')),
                ('number', models.IntegerField(default=0)),
                ('answer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.answermodel')),
            ],
        ),
        migrations.CreateModel(
            name='CommentTicketModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(default='T')),
                ('number', models.IntegerField(default=0)),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.ticketmodel')),
            ],
        ),
        migrations.DeleteModel(
            name='CommentModel',
        ),
    ]
