# Generated by Django 3.2.9 on 2022-02-10 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0021_auto_20220209_1858'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticketmodel',
            name='comments',
            field=models.TextField(default='Comment'),
        ),
    ]
