# Generated by Django 3.2.9 on 2022-02-10 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0023_auto_20220209_0851'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticketmodel',
            name='comments',
        ),
        migrations.AlterField(
            model_name='ticketmodel',
            name='priority',
            field=models.CharField(choices=[('1', 'Urgent'), ('2', 'High'), ('3', 'Medium'), ('4', 'Low')], default='3', max_length=1),
        ),
    ]
