# Generated by Django 3.2.9 on 2022-02-19 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0024_auto_20220210_1558'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticketmodel',
            name='file',
            field=models.FileField(null=True, upload_to='static/capture_files_folder/'),
        ),
    ]
