# Generated by Django 3.2.9 on 2022-03-07 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0030_answermodel_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='answermodel',
            name='lock',
            field=models.BooleanField(default=False),
        ),
    ]
