# Generated by Django 3.2.9 on 2022-03-11 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0031_answermodel_lock'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegisterAgent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(default='example@gmail.com', max_length=254)),
            ],
        ),
    ]
