# Generated by Django 3.2.9 on 2022-03-11 21:41

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0033_alter_ticketmodel_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answermodel',
            name='text',
            field=ckeditor.fields.RichTextField(blank=True),
        ),
    ]
