# Generated by Django 3.2.9 on 2022-03-11 23:35

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0034_alter_answermodel_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='answermodel',
            name='title',
            field=models.TextField(default='Title'),
        ),
        migrations.AlterField(
            model_name='answermodel',
            name='text',
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name='ticketmodel',
            name='text',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
