# Generated by Django 3.2.9 on 2022-03-13 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0035_auto_20220311_2335'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticketmodel',
            name='priority',
            field=models.CharField(choices=[('4', 'Low'), ('3', 'Medium'), ('2', 'High'), ('1', 'Urgent')], default='3', max_length=1),
        ),
    ]
