# Generated by Django 3.2.9 on 2022-03-16 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0036_alter_ticketmodel_priority'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticketmodel',
            name='status',
            field=models.CharField(choices=[('N', 'New'), ('O', 'Open'), ('C', 'Closed')], default='N', max_length=1),
        ),
    ]
