# Generated by Django 3.2.9 on 2022-03-19 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0037_alter_ticketmodel_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='commentanswermodel',
            name='author',
            field=models.TextField(default='Commentar'),
        ),
        migrations.AddField(
            model_name='commentticketmodel',
            name='author',
            field=models.TextField(default='Commentar'),
        ),
    ]
