# Generated by Django 3.2.9 on 2022-03-21 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0038_auto_20220319_1941'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RegisterAgent',
        ),
        migrations.AlterField(
            model_name='commentanswermodel',
            name='text',
            field=models.TextField(default='Text'),
        ),
        migrations.AlterField(
            model_name='commentticketmodel',
            name='text',
            field=models.TextField(default='Text'),
        ),
    ]
